### ISSUE TITLE
Add Public Methods to interface

### ISSUE THREAD

**Issue by alexz707** [samsonasik/ApigilityConsumer#8]
Hi! 
I'm using your client to connect to some api not written with apigility and it works ;)
But one thing I have seen is that the  ApigilityConsumer/src/Result/ClientResult.php
has the properties $data, $success and $messages.
Could you please add some getters for them to the interface so I can access them by using the interface and not the concrete clientresult ?

Thanks ;)
regards alex

**Comment by samsonasik** [comment]
Hi @alexz707 ,

Thank you for using it. ClientResult->success, ClientResult->data, ClientResult::$messages are public, so you can pull it from api call result:

```php
$clientResult = $clientService->callAPI(...);

var_dump($clientResult->success);
var_dump($clientResult->data);
var_dump($clientResult::$messages);
``` 

On what use case you want to do from getter ?

**Comment by alexz707** [comment]
hi! 
thanks for the fast response!
for example:

`public function getErrorMessageString(ResultInterface $result)
    {
        $resultStr = '';
        if(array_key_exists('http', $result::$messages))
        {
            foreach ($result::$messages['http'] as $key => $value)
            {
                $resultStr .= 'Error '.$key.' -> '. $value;
            }
        }
        return $resultStr;
    }`

it would be much more cleaner if there is a getter (ofc in the interface too) so I can use the interface.
otherwise I would have to use the concrete class:
`public function getErrorMessageString(ClientResult $result)`
and that's the thing I would like to avoid ;)

**Comment by samsonasik** [comment]
I choose to avoid doing that, actually, the implementation of what error string will be shown/used is up to the application that consume it.
You can extends and create your own method for consuming it.

**Comment by samsonasik** [comment]
Another reason to not add getters is that the ClientResult is intended to be used by ClientService privately and always be used after callAPI(), so, add getter() its properties will bring more condition on pre/post api call, and that will make possible bugs.

**Comment by alexz707** [comment]
I just had a look at the code but extending and using is not really possible because its concrete ($self = new self()) and the Result is also used concrete.

The callApi will return a ClientResult so I don't get your second point that it is used just privatley.
Or is there another way to check if the call was successfully? (atm I check if $success of the Result is true?)

**Comment by samsonasik** [comment]
The point is limit the `ClientResult` usage only by after api call. You can use : 

```php
$clientResult = $clientService->callAPI(...);
if ($clientResult->success) {
         // show data
         var_dump($clientResult->data);
} else {
       yourOwnMethodProcessErrorMessages($clientResult::$messages);
}
```

For your use case.

**Comment by alexz707** [comment]
Ok i got the point ;)
But your callAPI returns (at least in the doc)
just the interface so my ide will mark the ->data as invalid)
so that's why i would recommend to use a method ;)

**Comment by samsonasik** [comment]
`callAPI()` in `ClientApiInterface` is used by 2 class ( `ClientService` and `ClientAuthService` ), that's why it returns Resultinterface.
